### ISSUE TITLE
i don't really know where is the problem 

### ISSUE THREAD

**Issue by cherifburette** [msayed-net/localize_and_translate#9]
i made this function it should be working it checks if a shared preference has ar value and it should enter this function, it does enter the function but it some how exists in "to" part after checking it using the breakpoints 
![3b0376ab-2d03-46a9-914c-087a85774201](https://user-images.githubusercontent.com/49873734/82758520-55295600-9de7-11ea-8110-918285ac5ad6.jpg)
thanks in advance

**Comment by msayed-net** [comment]
The thing is Google translation API uses pay at scale for translations, it's not free.

When first I added this method I thought people will donate so that we could use more translations, but that did not happen.

Google limited usage for us now, so I removed this method in the newer versions of localize_and_translate and you will not get any further translations.

**Comment by cherifburette** [comment]
@msayed-net oh ok, so what is the new function ?

**Comment by msayed-net** [comment]
I'm studying adding all possible translation methods with user-based API-Keys, so that every user become responsible for his usage

**Comment by msayed-net** [comment]
Please check versions 3.x.x which applies mentioned method
